package com.bdu.clearance.enums;

public enum Department {
    COMPUTER_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    CHEMICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    SOFTWARE_ENGINEERING,
    COMPUTER_SCIENCE,
    CYBER_SECURITY,
    BUSINESS,
    ACCOUNTING,
    MANAGEMENT,
    MEDICINE,
    LAW,
    ARCHITECTURE,
    FASHION,
}
